### ISSUE TITLE
ob run: error - build failed

### ISSUE THREAD

**Issue by raptazure** [obsidiansystems/calculator-tutorial#6]
When I'm trying to `ob run` on macOS 10.15.7 (nix binary cache already set up), it gives the following error:
![image](https://user-images.githubusercontent.com/44319278/107664939-e4550180-6cc7-11eb-9fbc-080f612dfab3.png)

Is there a way to fix it? Thanks.

**Comment by dfordivam** [comment]
@raptazure 
As a workaround you may add the `dontCheck` override, like already done for some other libs in `default.nix`

```
  overrides = self: super: {
    temporary = dontCheck super.temporary;
    http-reverse-proxy = dontCheck super.http-reverse-proxy;
```

**Comment by raptazure** [comment]
> @raptazure
> As a workaround you may add the `dontCheck` override, like already done for some other libs in `default.nix`
> 
> ```
>   overrides = self: super: {
>     temporary = dontCheck super.temporary;
>     http-reverse-proxy = dontCheck super.http-reverse-proxy;
> ```

It works! Thanks! :)
